language: csharp
solution: ./TicTacToe/MyGame.sln
script:
  - xbuild /p:Configuration=Debug ./TicTacToe/MyGame.sln
before_install:
  - sudo apt-get install nunit-console

before_script:
  - nuget restore ./TicTacToe/MyGame.sln

after_script:
  - nunit-console ./TicTacToe/bin/Release/MyGame.dll