language: csharp
solution: ./TicTacToe/MyGame.sln

install:
  - nuget restore ./TicTacToe/MyGame.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild ./TicTacToe/MyGame.sln
  - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./MyPoject.Tests/bin/Release/MyProject.Tests.dll