language: csharp
solution: TicTacToe/MyGame.sln
install:
  - nuget restore TicTacToe/MyGame.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TicTacToe/MyGame.sln