language: csharp
solution: ./TicTacToe/MyGame.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore ./TicTacToe/MyGame.sln

script:
  - xbuild ./TicTacToe/MyGame.sln
  - nunit-console ./TicTacToe/MyGame.Tests/bin/Debug/MyGame.Tests.dll